stages:
  - check
  - build
  - test
  - push
  - docs

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

# Not making these global variables because they would get overridden in multi-project pipelines
.variables: &variables
  # The base of this repo's docker registry
  REPO_DOCKER_REGISTRY: ${CI_REGISTRY_IMAGE}
  # The image name of blaze image
  BLAZE_IMAGE:
    ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/blaze/blaze
  # Enable buildkit for more efficient layer caching
  DOCKER_BUILDKIT: "1"

# Potential build dependencies for the dind host
.script-bootstrap-dind: &script-bootstrap-dind
  - echo -e "section_start:`date +%s`:bootstrap[collapsed=true]\r\e[0KBootstrap build dependencies"
  - |
    if [ -f /etc/alpine-release ]; then
      apk add coreutils curl git jq python3
      apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/testing time
    fi
  - echo -e "section_end:`date +%s`:bootstrap\r\e[0K"

.job:
  tags:
    - dind
  timeout: 1h
  variables:
    <<: *variables
  before_script: &job-before-script
    - echo -e "section_start:`date +%s`:pre-env[collapsed=true]\r\e[0KEnvironment info (before_script)"
    - uname -a
    - env
    - ls -al
    - find . -maxdepth 1 \( ! -name . \) -print0 | sort -z | xargs -0 -x du -bhsc
    - df -h
    - date -Iseconds
    - |
      if type jq >/dev/null; then
        echo 'Docker Hub ratelimit:'
        curl -s --head -H "Authorization: Bearer $(curl -s 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull' | jq -r .token)" \
          https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest | grep ^ratelimit
      fi
    - |
      if type git >/dev/null; then
        pushd "$BLAZE_BINJA_API" >/dev/null && \
          { git log --color --decorate HEAD^..HEAD | cat || true;
            popd >/dev/null;
          } || true
      fi
    - |
      if type python3 >/dev/null; then
        python3 -c 'import binaryninja; print(binaryninja.core_version())' || true
      fi
    - echo -e "section_end:`date +%s`:pre-env\r\e[0K"

.docker-job:
  extends: .job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind
  before_script:
    - *script-bootstrap-dind
    - *job-before-script
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"


.haskell-job:
  extends: .job
  image: ${REPO_DOCKER_REGISTRY}/blaze-service:pipeline-${CI_PIPELINE_IID}

.python-job:
  extends: .job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.10-slim
  before_script:
    - *job-before-script
    - echo -e "section_start:`date +%s`:setup-python[collapsed=true]\r\e[0KSet up python dependencies"
    - pushd binja_plugin >/dev/null
    - poetry install
    - source "$(poetry env info --path)"/bin/activate
    - popd >/dev/null
    - echo -e "section_end:`date +%s`:setup-python\r\e[0K"

lint:server:
  stage: check
  extends: .job
  image: ${BLAZE_IMAGE}
  needs: []
  script:
    - hlint --color=always server/src server/test
  allow_failure: true

typecheck:plugin:warnings:
  stage: check
  extends: .python-job
  image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/devops/binaryninja-python-base:latest
  needs: []
  script:
    - cd binja_plugin
    - FORCE_COLOR=2 pyright --warnings
  allow_failure: true

typecheck:plugin:errors:
  stage: check
  extends: .python-job
  image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/devops/binaryninja-python-base:latest
  needs: []
  script:
    - cd binja_plugin
    - FORCE_COLOR=2 pyright

build:
  stage: build
  extends: .docker-job
  needs: []
  script:
    - blaze_image=${REPO_DOCKER_REGISTRY}/blaze-service
    - minimal_blaze_image=${REPO_DOCKER_REGISTRY}/blaze-service/minimal
    - wheel_server_image=${REPO_DOCKER_REGISTRY}/blaze-wheel-server

    # Pull images for layer caching
    - echo -e "section_start:`date +%s`:docker-pull[collapsed=true]\r\e[0KPull docker images for caching"
    - docker pull "${blaze_image}:latest" || true
    - docker pull "${wheel_server_image}:latest" || true
    - echo -e "section_end:`date +%s`:docker-pull\r\e[0K"

    # Build images
    - echo -e "section_start:`date +%s`:docker-build\r\e[0KBuild docker images"
    - if [ "${CI_COMMIT_BRANCH}" = "${CI_DEFAULT_BRANCH}" ]; then
        build_type=release;
      else
        build_type=dev;
      fi
    - docker build --pull . -f Dockerfile --target main
      --build-arg "BUILD_TYPE=${build_type}"
      --build-arg STACK_BUILD_OPTIONS="--ghc-options=-fdiagnostics-color=always"
      -t "${blaze_image}:pipeline-${CI_PIPELINE_IID}"
    - docker build --pull . -f Dockerfile --target minimal
      --build-arg "BUILD_TYPE=${build_type}"
      --build-arg STACK_BUILD_OPTIONS="--ghc-options=-fdiagnostics-color=always"
      -t "${minimal_blaze_image}:pipeline-${CI_PIPELINE_IID}"
    - docker build --pull . -f Dockerfile --target wheel-server
      --build-arg CI_PIPELINE_ID="${CI_PIPELINE_ID}"
      -t "${wheel_server_image}:pipeline-${CI_PIPELINE_IID}"
    - echo -e "section_end:`date +%s`:docker-build\r\e[0K"

    # Push images
    - echo -e "section_start:`date +%s`:docker-push[collapsed=true]\r\e[0KPush new docker images"
    - docker push "${blaze_image}:pipeline-${CI_PIPELINE_IID}"
    - docker push "${minimal_blaze_image}:pipeline-${CI_PIPELINE_IID}"
    - docker push "${wheel_server_image}:pipeline-${CI_PIPELINE_IID}"
    - echo -e "section_end:`date +%s`:docker-push\r\e[0K"

test:
  stage: test
  extends: .haskell-job
  needs:
    - build
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cp -T "${BLAZE_BINJA_LICENSE_FILE}" /root/.binaryninja/license.dat
    - cd /blaze/build/blaze-ui/server
    - ../.ci/scripts/run_test.py ~/.local/bin/blaze-server-test

push:latest:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: manual
      allow_failure: true
  needs:
    - test
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - gitlab_blaze=${REPO_DOCKER_REGISTRY}/blaze-service/minimal
    - gitlab_wheel_server=${REPO_DOCKER_REGISTRY}/blaze-wheel-server

    # Pull this pipeline's images
    - echo -e "section_start:`date +%s`:docker-pull\r\e[0KPull latest docker images"
    - docker pull "${gitlab_blaze}:pipeline-${CI_PIPELINE_IID}"
    - docker pull "${gitlab_wheel_server}:pipeline-${CI_PIPELINE_IID}"
    - echo -e "section_end:`date +%s`:docker-pull\r\e[0K"

    # Push :latest tags to internal gitlab registry
    - echo -e "section_start:`date +%s`:docker-push-gitlab\r\e[0KPush latest docker images to gitlab"
    - docker tag "${gitlab_blaze}:pipeline-${CI_PIPELINE_IID}" "${gitlab_blaze}:latest"
    - docker push "${gitlab_blaze}:latest"
    - docker tag "${gitlab_wheel_server}:pipeline-${CI_PIPELINE_IID}" "${gitlab_wheel_server}:latest"
    - docker push "${gitlab_wheel_server}:latest"
    - echo -e "section_end:`date +%s`:docker-push-gitlab\r\e[0K"

push:tag:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_TAG
  needs:
    - test
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - gitlab_blaze=${REPO_DOCKER_REGISTRY}/blaze-service/minimal
    - gitlab_wheel_server=${REPO_DOCKER_REGISTRY}/blaze-wheel-server

    # Pull this pipeline's images
    - echo -e "section_start:`date +%s`:docker-pull\r\e[0KPull latest docker images"
    - docker pull "${gitlab_blaze}:pipeline-${CI_PIPELINE_IID}"
    - docker pull "${gitlab_wheel_server}:pipeline-${CI_PIPELINE_IID}"
    - echo -e "section_end:`date +%s`:docker-pull\r\e[0K"

    # Push :tag-FOO images to internal gitlab registry
    - echo -e "section_start:`date +%s`:docker-push-gitlab\r\e[0KPush latest docker images to gitlab"
    - docker tag "${gitlab_blaze}:pipeline-${CI_PIPELINE_IID}" "${gitlab_blaze}:tag-${CI_COMMIT_TAG}"
    - docker push "${gitlab_blaze}:tag-${CI_COMMIT_TAG}"
    - docker tag "${gitlab_wheel_server}:pipeline-${CI_PIPELINE_IID}" "${gitlab_wheel_server}:tag-${CI_COMMIT_TAG}"
    - docker push "${gitlab_wheel_server}:tag-${CI_COMMIT_TAG}"
    - echo -e "section_end:`date +%s`:docker-push-gitlab\r\e[0K"

pages:
  extends: .docker-job
  stage: docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_ID == null
      when: on_success
    - if: $CI_MERGE_REQUEST_ID == null
      when: manual
      allow_failure: true
  needs:
    - test
  variables:
    <<: *variables
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze-ui
    - docker build --pull .
      --build-arg "CI_REGISTRY=${CI_REGISTRY}"
      --build-arg "CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}"
      --target docs
      -t "${image}/docs:pipeline-${CI_PIPELINE_IID}"
    - rm -rf public
    - mkdir public
    - docker run --rm -v $PWD/public:/public "${image}/docs:pipeline-${CI_PIPELINE_IID}" tar -cvC server/docs . | tar -xvC public --no-same-owner
  artifacts:
    paths:
      - public
    expire_in: 12 hours

cleanup:
  stage: .post
  when: always
  extends: .docker-job
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache --update bash
    - "# Untag all images created by this pipeline so we don't waste space on CI runner"
    - |
      bash -c '
        images=(
          ${REPO_DOCKER_REGISTRY}/blaze-service
          ${REPO_DOCKER_REGISTRY}/blaze-service/minimal
          ${REPO_DOCKER_REGISTRY}/blaze-wheel-server
          )
        tags=()
        for image in "${images[@]}"; do
          tags+=(
            "${image}:pipeline-${CI_PIPELINE_IID}"
            "${CI_COMMIT_TAG:+${image}:tag-${CI_COMMIT_TAG}}"
            )
        done
        for i in "${!tags[@]}"; do if [ -z "${tags[$i]}" ]; then unset tags[$i]; fi; done
        echo "${tags[@]}"
        docker image rm "${tags[@]}" || true
      '
