version: "3"

services:
  blaze-server:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/blaze-ui/blaze-service/squashed
    # image: 077943246560.dkr.ecr.us-east-2.amazonaws.com/integrated_blaze_system/kudu/blaze-service
    volumes:
      - blaze:/blaze/persistent
    ports:
      - 31337:31337
      - 31338:31338
    environment:
      - BLAZE_UI_HOST=0.0.0.0
      - BLAZE_UI_WS_PORT=31337
      - BLAZE_UI_HTTP_PORT=31338
      - BLAZE_UI_SQLITE_FILEPATH=/blaze/persistent/blaze.sqlite
      - BLAZE_UI_BNDB_STORAGE_DIR=/blaze/persistent/bndbs
    command: ["/blaze/bin/blaze-server"]

volumes:
  blaze:
