resolver: lts-18.5
compiler: ghc-8.10.4

packages:
  - .
  
extra-deps:
  - ../../blaze
  - ../../binaryninja-haskell
  - ../../binary-analysis
  - git: https://github.com/mpdairy/purescript-bridge
    commit: a55ece4e5a5d1a3cde5302ef449e3c9f2963d9a7
  -  dom-lt-0.2.0@sha256:fc7451d6ada55233239d22b6eed8f2e4c1c1290f1cad101c9d429ea875aa72e6,1615
  - weeder-2.1.3
ghc-options:
  "$locals": -fwrite-ide-info
    #-ddump-to-file -ddump-hi
