#!/bin/bash

set -euo pipefail
shopt -s nullglob

PACKAGE_NAME=${PACKAGE_NAME:-blaze}

if [[ -z $BLAZE_WHEEL_SERVER_URL ]]; then
    echo "USAGE: BLAZE_WHEEL_SERVER_URL=<SERVER_URL> $0" >&2
    exit 1
fi

base_url=$BLAZE_WHEEL_SERVER_URL
wheels=("${PACKAGE_NAME}"-[0-9]*.whl)
if [[ ${#wheels[@]} -eq 0 ]]; then
    echo "No matching wheels found" >&2
    exit 1
elif [[ ${#wheels[@]} -ne 1 ]]; then
    echo "Too many matching wheels: ${wheels[*]}" >&2
    exit 1
fi
wheel=${wheels[0]}
url=$base_url/$wheel

echo "Found wheel: $wheel"
echo "Setting wheel URL: $url"

jq --arg packageUrl "$url" '.[0].packageUrl = $packageUrl' <plugins.json \
    | sponge plugins.json

echo "Starting wheel server"
exec /usr/bin/hastatic
